# Generated by Django 3.2.7 on 2023-04-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_sensordata_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='owner',
            new_name='timestep',
        ),
    ]
