# Generated by Django 3.2.7 on 2023-04-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_owner_sensordata_timestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='timestep',
        ),
    ]
