# Generated by Django 3.2.7 on 2023-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_sensordata_timestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestep',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
